name: Next.js CI/CD Pipeline
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run lint checks
      # - name: Lint code
      #   run: npm run lint

      # Step 5: Run tests and coverage checks
      # - name: Run tests and check coverage
      #   run: npm run test && npm run coverage-check

      # Steps 4 & 5 in 1 step
      - name: Validate code quality
        run: npm run validate

      # Step 6: Build the Next.js app
      - name: Build the app
        run: npm run build

      # Step 7: Deploy to Vercel
      - name: Deploy to Vercel
        if: ${{ success() }} # Ensure deployment only happens if previous steps pass
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
